import type { Locale } from '../shared/contracts';

export const productionText = {
  th: {
    importAudio: 'นำเข้าเสียง',
    title: 'วางแผนการผลิต', loading: 'กำลังโหลดข้อมูล', matching: 'กำลังจับคู่ชื่อไฟล์', loadFailed: 'โหลดข้อมูลไม่สำเร็จ', saveSuccess: 'บันทึกแล้ว', saveAndExport: 'บันทึกและส่งออก', missingClips: 'ยังมีฉากที่ไม่มีคลิปนำเข้า', fileLimit: 'เลือกไฟล์ได้สูงสุด 12 ไฟล์ (ไฟล์ละไม่เกิน 128 MiB)', duplicates: 'ชื่อไฟล์ต้องไม่ซ้ำกัน', targetConflict: 'เลือกฉากที่ไม่ซ้ำกันและไม่มีคลิปอยู่แล้ว', flow: 'การตั้งค่า Google Flow', model: 'รุ่นโมเดล', rate: 'เครดิตต่อการสร้าง', duration: 'ระยะเวลาต่อคลิป (วินาที)', budget: 'งบเครดิต', verified: 'ยืนยันอัตราเครดิตและงบประมาณแล้ว', save: 'บันทึกการตั้งค่า', generations: 'จำนวนครั้งที่คาดการณ์', estimate: 'เครดิตโดยประมาณ', within: 'อยู่ในงบประมาณ', unknown: 'ยังประเมินไม่ได้', noSpend: 'หน้าจอนี้ไม่ใช้เครดิตและไม่เรียกเก็บเงิน การสร้างคลิปทำโดยคุณใน Google Flow', openFlow: 'เปิด Google Flow', scene: 'ฉาก', prompt: 'พรอมป์ภาษาอังกฤษสำหรับ Flow', copy: 'คัดลอกพรอมป์', status: 'สถานะฉาก', planned: 'วางแผนแล้ว', ready_for_flow: 'พร้อมส่งไป Flow', generating: 'กำลังสร้าง', failed: 'ไม่สำเร็จ', character: 'รหัสอ้างอิงตัวละคร', location: 'รหัสอ้างอิงสถานที่', notes: 'บันทึก', saveScene: 'บันทึกฉาก', imported: 'มีคลิปนำเข้าแล้ว', match: 'จับคู่และนำเข้าคลิป', chooseFiles: 'เลือกไฟล์วิดีโอ', confirm: 'ยืนยันการนำเข้า', filename: 'ไฟล์', target: 'ฉากปลายทาง', noScene: 'ไม่จับคู่', unmatched: 'ไม่พบฉากจากชื่อไฟล์', upload: 'นำเข้าคลิป', uploading: 'กำลังนำเข้า', validation: 'กรุณาตรวจสอบข้อมูลที่กรอก', uploadError: 'นำเข้าไฟล์ไม่สำเร็จ', audio: 'เสียงประกอบ', editor: 'ตั้งค่าตัดต่อ', resolution: 'ความละเอียด', quality: 'คุณภาพ', draft: 'ร่าง', standard: 'มาตรฐาน', high: 'สูง', transition: 'รอยต่อฉาก', cut: 'ตัด', fade: 'เฟด', normalize: 'ปรับระดับเสียงให้สม่ำเสมอ', clipVolume: 'ระดับเสียงคลิป', music: 'เพลงประกอบ', musicVolume: 'ระดับเสียงเพลง', subtitles: 'คำบรรยาย', off: 'ปิด', languageThai: 'ไทย', languageEnglish: 'อังกฤษ', effects: 'เสียงเอฟเฟกต์', addEffect: 'เพิ่มเสียงเอฟเฟกต์', remove: 'ลบ', asset: 'ไฟล์เสียง', sceneTarget: 'ฉาก', volume: 'ระดับเสียง', order: 'ลำดับฉาก', up: 'เลื่อนขึ้น', down: 'เลื่อนลง', audioUpload: 'อัปโหลดเสียง (MP3, WAV, M4A, OGG; ไม่เกิน 32 MiB)', loaded: 'ไฟล์เสียงที่มี', seconds: 'วินาที', saveEditor: 'บันทึกการตัดต่อ',
  },
  en: {
    importAudio: 'Import audio',
    title: 'Production planning', loading: 'Loading production data', matching: 'Matching filenames', loadFailed: 'Could not load production data', saveSuccess: 'Saved', saveAndExport: 'Save and export', missingClips: 'Some scenes still have no imported clip', fileLimit: 'Select up to 12 files (128 MiB each)', duplicates: 'Filenames must be unique', targetConflict: 'Choose distinct scenes without an existing clip', flow: 'Google Flow settings', model: 'Model', rate: 'Credits per generation', duration: 'Generation duration (seconds)', budget: 'Credit budget', verified: 'Owner verified the credit rate and budget', save: 'Save settings', generations: 'Estimated generations', estimate: 'Estimated credits', within: 'Within budget', unknown: 'Unavailable', noSpend: 'This screen does not spend credits or charge you. You create clips yourself in Google Flow.', openFlow: 'Open Google Flow', scene: 'Scene', prompt: 'English Flow prompt', copy: 'Copy prompt', status: 'Scene status', planned: 'Planned', ready_for_flow: 'Ready for Flow', generating: 'Generating', failed: 'Failed', character: 'Character reference ID', location: 'Location reference ID', notes: 'Notes', saveScene: 'Save scene', imported: 'Clip imported', match: 'Match and import clips', chooseFiles: 'Choose video files', confirm: 'Confirm import', filename: 'File', target: 'Target scene', noScene: 'Do not match', unmatched: 'No scene detected from filename', upload: 'Import clip', uploading: 'Importing', validation: 'Check the entered values', uploadError: 'File import failed', audio: 'Audio assets', editor: 'Editor settings', resolution: 'Resolution', quality: 'Quality', draft: 'Draft', standard: 'Standard', high: 'High', transition: 'Scene transition', cut: 'Cut', fade: 'Fade', normalize: 'Normalize audio', clipVolume: 'Clip volume', music: 'Music', musicVolume: 'Music volume', subtitles: 'Subtitles', off: 'Off', languageThai: 'Thai', languageEnglish: 'English', effects: 'Sound effects', addEffect: 'Add effect', remove: 'Remove', asset: 'Audio asset', sceneTarget: 'Scene', volume: 'Volume', order: 'Scene order', up: 'Move up', down: 'Move down', audioUpload: 'Upload audio (MP3, WAV, M4A, OGG; max 32 MiB)', loaded: 'Available audio', seconds: 'seconds', saveEditor: 'Save editor settings',
  },
} satisfies Record<Locale, Record<string, string>>;

export function pt(locale: Locale, key: keyof typeof productionText.en): string { return productionText[locale][key]; }
